type: unsort
channel: 1024
train: 
  nezha: 
    20240314: #不能以0开头
      v_angle: 
        - 0
    20240315: 
      v_angle: 
        - 0
    20240320: 
      v_angle: 
        - 0
    20240321: 
      v_angle: 
        - 0
test:
  nezha:  
    20240322: 
      v_angle: 
        - 0
